### PR TITLE
make constructor of Content public

### PR DESCRIPTION
**Pull request by cash**
I'm creating my own ResponseHandler when using the fluent API and would like to return a Content object. The Content constructor is private to the package and I'd rather not have to put my response handler into the fluent package. My best alternative right now is copy the Content class. It would be much nicer if this handy little class was updated.

### CODE REVIEW

**Comment by garydgregory** [comment]
I'm OK with that. Oleg? Should we make the ctor public or add a factory method?

**Comment by cash** [comment]
I haven't noticed the use of factory methods in the fluent API so for the sake of consistency, I think making the constructor public is the right option. @ok2c

**Comment by ok2c** [comment]
I am certainly fine with it, but we ought not add new methods to stable branches like 4.5.x. Trunk is a whole different story.

**Comment by garydgregory** [comment]
commit -m "[HTTPCLIENT-1717] Make fluent API .Content.Content(byte[], ContentType) public." -N E:/vcs/svn/apache/httpcomponents/branches/4.5.x/httpclient/RELEASE_NOTES.txt E:/vcs/svn/apache/httpcomponents/branches/4.5.x/httpclient/fluent-hc/src/main/java/org/apache/http/client/fluent/Content.java
    Sending        E:/vcs/svn/apache/httpcomponents/branches/4.5.x/httpclient/RELEASE_NOTES.txt
    Sending        E:/vcs/svn/apache/httpcomponents/branches/4.5.x/httpclient/fluent-hc/src/main/java/org/apache/http/client/fluent/Content.java
    Transmitting file data ...
    Committed revision 1728787.

**Comment by garydgregory** [comment]
```
commit -m "[HTTPCLIENT-1717] Make fluent API .Content.Content(byte[], ContentType) public." -N E:/vcs/svn/apache/httpcomponents/trunk/httpclient/httpclient5-fluent/src/main/java/org/apache/hc/client5/http/fluent/Content.java E:/vcs/svn/apache/httpcomponents/trunk/httpclient/RELEASE_NOTES.txt
    Sending        E:/vcs/svn/apache/httpcomponents/trunk/httpclient/RELEASE_NOTES.txt
    Sending        E:/vcs/svn/apache/httpcomponents/trunk/httpclient/httpclient5-fluent/src/main/java/org/apache/hc/client5/http/fluent/Content.java
    Transmitting file data ...
    Committed revision 1728788.

```

**Comment by garydgregory** [comment]
Committed to trunk and 4.5.x branch. Please verify and close.

**Comment by cash** [comment]
Thanks

**Pull request closed without merging**
